

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/QLNV_PHP/src/public/css/activity.css" type="text/css"/> 
</head>
<body>
    <?php if (!empty($message)): ?>
        <div class="notification-wrapper">
            <div class="notification">
                <span class="close" onclick="this.parentElement.parentElement.style.display='none';">&times;</span>
                <?php echo htmlspecialchars($message); ?>
            </div>
        </div>
    <?php endif; ?>
    <main>
        <div class="container">
            <h1 class="mb-4">Danh sách hoạt động</h1>  
            <div class="row">
                <div class="col-md-8">
                    <div class="activity-summary" style="z-index: 0;">
                        <div class="total-activities">
                            <div><img src="/QLNV_php/src/public/img/logo/activity_in_month.png" alt="icon"> Tổng hoạt động</div>
                            <div><h2><?php echo htmlspecialchars($countAllActivity); ?></h2></div>
                        </div>
                        <div class="ongoing-activities">
                            <div><img src="/QLNV_php/src/public/img/logo/activity_now.png" alt="icon"> Số hoạt động đang diễn ra</div>
                            <div><h2><?php echo htmlspecialchars($countActivityByMonth); ?></h2></div>
                        </div>
                        <div class="activity-list">
                            <h4>Danh sách các hoạt động bạn đã tham gia:</h4>
                            <ul>
                                <?php if (!empty($pagedActivities)): ?>
                                    <?php foreach ($pagedActivities as $activity): ?>
                                        <div id="activityTG" class="activity-item" >
                                            
                                        </div>
                                    <?php endforeach; ?>
                                <?php else:?>
                                    <div>Không có<br>
                                <?php endif; ?>
                            </ul>
                            <?php if ($totalPages > 1): ?>
                                <ul id="paginationTG" class="pagination">
                                    <?php for ($i = 1; $i <= $totalPages; $i++): ?>
                                        <li class="page-item <?php echo ($i === $currentPage) ? 'active' : ''; ?>">
                                            <a class="page-link" href="?action=<?php echo htmlspecialchars($_GET['action']); ?>&page=<?php echo $i; ?>&searchcb=<?php echo htmlspecialchars($searchCB); ?>&searchlk=<?php echo htmlspecialchars($searchLK); ?>&pageCB=<?php echo $currentPageCB; ?>&pageLK=<?php echo $currentPageLK; ?>&pageTT=<?php echo $currentPageTT; ?>">
                                                <?php echo $i; ?>
                                            </a>
                                        </li>
                                    <?php endfor; ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                        <br>
                        <div class="activity-list">
                            <h4>Danh sách các hoạt động, chiến dịch trong tháng:</h4>
                            <ul>
                                <?php if (!empty($pagedActivities)): ?>
                                    <?php foreach ($pagedActivities as $activity): ?>
                                        <div id="activityTT"  class="activity-item" >
                                            
                                        </div>
                                    <?php endforeach; ?>
                                <?php else:?>
                                    <div>Không có<br>
                                <?php endif; ?>
                            </ul>
                            <?php if ($totalPagesTT > 1): ?>
                                <ul id="paginationTT" class="pagination">
                                    <?php for ($i = 1; $i <= $totalPagesTT; $i++): ?>
                                        <li class="page-item <?php echo ($i === $currentPageTT) ? 'active' : ''; ?>">
                                            <a class="page-link" href="?action=<?php echo htmlspecialchars($_GET['action']); ?>&pageTT=<?php echo $i; ?>&searchcb=<?php echo htmlspecialchars($searchCB); ?>&searchlk=<?php echo htmlspecialchars($searchLK); ?>&pageCB=<?php echo $currentPageCB; ?>&pageLK=<?php echo $currentPageLK; ?>&page=<?php echo $currentPage; ?>">
                                                <?php echo $i; ?>
                                            </a>
                                        </li>
                                    <?php endfor; ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="activity-list" style="width: 600px;">
                        <h4>Hoạt động cơ bản:</h4>
                        <div class="search-wrapper">
                            <input type="text" id="search-box" name="searchcb" class="form-control search-bar" placeholder="Tên hoạt động cơ bản..." value="<?php echo htmlspecialchars($searchCB); ?>">
                        </div>
                        <?php if (!empty($pagedActivitiesCB)): ?>
                            <?php foreach ($pagedActivitiesCB as $activity): ?>
                                <div id="activityCB" class="activity-item" >
                                
                                </div>
                            <?php endforeach; ?>
                        <?php else:?>
                            <div>Không có<br>
                        <?php endif; ?>
                        <br>
                        <?php if ($totalPagesCB > 1): ?>
                            <ul id="paginationCB" class="pagination">
                                
                            </ul>
                        <?php endif; ?>
                    </div>

                    <div class="activity-list mt-4" style="width: 600px;">
                        <h4>Hoạt động liên kết:</h4>
                        <form method="get" action="">
                            <input type="text" id="searchlk" name="searchlk" class="form-control search-bar" placeholder="Tên hoạt động liên kết..." value="<?php echo htmlspecialchars($searchLK); ?>">
                        </form>
                        <?php if (!empty($pagedActivitiesLK)): ?>
                            <?php foreach ($pagedActivitiesLK as $activity): ?>
                                <div id="activityLK" class="activity-item">
                                <?php
                                    $statusColor = '#bdbdbd';

                                    switch ($activity['TinhTrang']) {
                                        case 'Chờ Đăng ký':
                                            $statusColor = '#ff9900';
                                            break;
                                        case 'Sắp diễn ra':
                                            $statusColor = '#00bfff';
                                            break;
                                        case 'Đang diễn ra':
                                            $statusColor = '#32cd32';
                                            break;
                                        case 'Kết Thúc':
                                            $statusColor = '#ff6347';
                                            break;
                                        case 'Chưa xác định':
                                            $statusColor = '#bdbdbd';
                                            break;
                                    }
                                    ?>
                                    <div><?php echo htmlspecialchars($activity['tenHoatDong']); ?><br>
                                    <small>Hạn chót đăng ký: <?php echo htmlspecialchars($activity['hanCuoiDangKy']); ?></small><br>
                                    <small>Ngày bắt đầu: <?php echo htmlspecialchars($activity['ngayBatDau']); ?> - Ngày kết thúc: <?php echo htmlspecialchars($activity['ngayKetThuc']); ?></small></div>
                                    <div class="status" style="background-color: <?php echo $statusColor; ?>;">
                                        <?php echo htmlspecialchars($activity['TinhTrang']); ?>
                                    </div>
                                    <br>
                                </div>
                            <?php endforeach; ?>
                        <?php else:?>
                            <div>Không có<br>
                        <?php endif; ?>
                        <br>
                        <?php if ($totalPagesLK > 1): ?>
                            <ul id="paginationLK" class="pagination">
                                <?php for ($i = 1; $i <= $totalPagesLK; $i++): ?>
                                    <li class="page-item <?php echo ($i === $currentPageLK) ? 'active' : ''; ?>">
                                        <a class="page-link" href="?action=<?php echo htmlspecialchars($_GET['action']); ?>&pageLK=<?php echo $i; ?>&searchlk=<?php echo htmlspecialchars($searchLK); ?>&searchcb=<?php echo htmlspecialchars($searchCB); ?>&pageTT=<?php echo $currentPageTT; ?>&pageCB=<?php echo $currentPageCB; ?>&page=<?php echo $currentPage; ?>">
                                            <?php echo $i; ?>
                                        </a>
                                    </li>
                                <?php endfor; ?>
                            </ul>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
    var currentPage = <?php echo $currentPage; ?>;
    var currentPageCB = <?php echo $currentPageCB; ?>;
    var currentPageLK = <?php echo $currentPageLK; ?>;
    var currentPageTT = <?php echo $currentPageTT; ?>;

    $('.search-box').off('input change').on('input change', function() { 
        loadActivities();
    });

    function loadActivities(page, pageCB, pageLK, pageTT) {
        var searchTerm = $('#search-box').val();
        console.log(searchTerm);

        $.ajax({
            url: 'index.php?action=GetActivityPage&ajax=true',
            type: 'GET',
            data: {
                page: page,
                pageTT: pageTT,
                pageCB: pageCB,
                pageLK: pageLK,
                searchcb: searchTerm,
                searchlk: $('#searchlk').val()
            },
            success: function(response) {
                console.log(response);
                var data = JSON.parse(response);
                // Cập nhật danh sách tham gia
                var activityHtml = '';
                $.each(data.activitiesTG, function(index, activity) {
                    var statusColor = getStatusColor(activity.TinhTrang);
                    activityHtml += '<div class="activity-item" onclick="location.href=\'/QLNV_PHP/src/index.php?action=GetActivityDetail&activityId=' + encodeURIComponent(activity.activityID) + '\';">';
                    activityHtml += '<div>' + activity.tenHoatDong + '<br><small>Hạn chót đăng ký: ' + activity.hanCuoiDangKy + '</small><br>';
                    activityHtml += '<small>Ngày bắt đầu: ' + activity.ngayBatDau + ' - Ngày kết thúc: ' + activity.ngayKetThuc + '</small></div>';
                    activityHtml += '<div class="status" style="background-color: ' + statusColor + ';">' + activity.TinhTrang + '</div>';
                    activityHtml += '<br></div>';
                });
                $('#activityTG').html(activityHtml);

                var paginationHtml = '';
                for (var i = 1; i <= data.totalPagesTG; i++) {
                    paginationHtml += '<li class="page-item ' + (i === page ? 'active' : '') + '"><a class="page-link" href="#" data-page-tg="' + i + '">' + i + '</a></li>';
                }
                $('#paginationTG').html(paginationHtml);
                console.log(paginationHtml);

                // Cập nhật danh sách theo tháng
                var activityTTHtml = '';
                $.each(data.activitiesTT, function(index, activity) {
                    var statusColor = getStatusColor(activity.TinhTrang);
                    activityTTHtml += '<div class="activity-item" onclick="location.href=\'/QLNV_PHP/src/index.php?action=GetActivityDetail&activityId=' + encodeURIComponent(activity.activityID) + '\';">';
                    activityTTHtml += '<div>' + activity.tenHoatDong + '<br><small>Hạn chót đăng ký: ' + activity.hanCuoiDangKy + '</small><br>';
                    activityTTHtml += '<small>Ngày bắt đầu: ' + activity.ngayBatDau + ' - Ngày kết thúc: ' + activity.ngayKetThuc + '</small></div>';
                    activityTTHtml += '<div class="status" style="background-color: ' + statusColor + ';">' + activity.TinhTrang + '</div>';
                    activityTTHtml += '<br></div>';
                });
                $('#activityTT').html(activityTTHtml);

                var paginationTTHtml = '';
                for (var i = 1; i <= data.totalPagesTT; i++) {
                    paginationTTHtml += '<li class="page-item ' + (i === pageTT ? 'active' : '') + '"><a class="page-link" href="#" data-page-tt="' + i + '">' + i + '</a></li>';
                }
                $('#paginationTT').html(paginationTTHtml);
                console.log(paginationTTHtml);

                // Cập nhật danh sách hoạt động cơ bản
                var activityCBHtml = '';
                $.each(data.activitiesCB, function(index, activity) {
                    var statusColor = getStatusColor(activity.TinhTrang);
                    activityCBHtml += '<div class="activity-item" onclick="location.href=\'/QLNV_PHP/src/index.php?action=GetActivityDetail&activityId=' + (activity.activityID) + '\';">';
                    activityCBHtml += '<div>' + activity.tenHoatDong + '<br><small>Hạn chót đăng ký: ' + activity.hanCuoiDangKy + '</small><br>';
                    activityCBHtml += '<small>Ngày bắt đầu: ' + activity.ngayBatDau + ' - Ngày kết thúc: ' + activity.ngayKetThuc + '</small></div>';
                    activityCBHtml += '<div class="status" style="background-color: ' + statusColor + ';">' + activity.TinhTrang +  '</div>';
                    activityCBHtml += '<br></div>';
                });
                $('#activityCB').html(activityCBHtml);

                // Cập nhật phân trang hoạt động cơ bản
                var paginationCBHtml = '';
                for (var i = 1; i <= data.totalPagesCB; i++) {
                    paginationCBHtml += '<li class="page-item ' + (i === pageCB ? 'active' : '') + '"><a class="page-link" href="#" data-page-cb="' + i + '">' + i + '</a></li>';
                }
                $('#paginationCB').html(paginationCBHtml);

                // Cập nhật danh sách hoạt động liên kết
                var activityLKHtml = '';
                $.each(data.activitiesLK, function(index, activity) {
                    var statusColor = getStatusColor(activity.TinhTrang);
                    activityLKHtml += '<div class="activity-item" onclick="location.href=\'/QLNV_PHP/src/index.php?action=GetActivityDetail&activityId=' + encodeURIComponent(activity.activityID) + '\';">';
                    activityLKHtml += '<div>' + activity.tenHoatDong + '<br><small>Hạn chót đăng ký: ' + activity.hanCuoiDangKy + '</small><br>';
                    activityLKHtml += '<small>Ngày bắt đầu: ' + activity.ngayBatDau + ' - Ngày kết thúc: ' + activity.ngayKetThuc + '</small></div>';
                    activityLKHtml += '<div class="status" style="background-color: ' + statusColor + ';">' + activity.TinhTrang + '</div>';
                    activityLKHtml += '<br></div>';
                });
                $('#activityLK').html(activityLKHtml);

                // Cập nhật phân trang hoạt động liên kết
                var paginationLKHtml = '';
                for (var i = 1; i <= data.totalPagesLK; i++) {
                    paginationLKHtml += '<li class="page-item ' + (i === pageLK ? 'active' : '') + '"><a class="page-link" href="#" data-page-lk="' + i + '">' + i + '</a></li>';
                }
                $('#paginationLK').html(paginationLKHtml);
            }
        });
    }

    function getStatusColor(status) {
        switch (status) {
            case 'Chờ Đăng ký': return '#ff9900';
            case 'Sắp diễn ra': return '#00bfff';
            case 'Đang diễn ra': return '#32cd32';
            case 'Kết Thúc': return '#ff6347';
            case 'Chưa xác định': return '#bdbdbd';
            default: return '#bdbdbd';
        }
    }

    $(document).on('click', '.page-link', function(e) {
        e.preventDefault();
        // var page = $(this).data('page-tg') || 1;
        // var pageTT = $(this).data('page-tt') || 1;
        // var pageCB = $(this).data('page-cb') || 1;
        // var pageLK = $(this).data('page-lk') || 1;
        var newPageTG = $(this).data('page-tg');
        var newPageTT = $(this).data('page-tt');
        var newPageCB = $(this).data('page-cb');
        var newPageLK = $(this).data('page-lk');
        if (newPageTG !== undefined) {
            currentPage = newPageTG;
        }
        if (newPageTT !== undefined) {
            currentPageTT = newPageTT;
        }
        if (newPageCB !== undefined) {
            currentPageCB = newPageCB;
        }
        if (newPageLK !== undefined) {
            currentPageLK = newPageLK;
        }
        loadActivities( currentPage, currentPageCB, currentPageLK, currentPageTT);
    });

    //Load dữ liệu khi trang được tải lần đầu
    loadActivities(currentPage, currentPageCB, currentPageLK, currentPageTT);
});
</script>
</body>
</html>


