<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yêu cầu</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="/QLNV_PHP/src/public/css/point_nv.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="info-box">
                <p><strong>Tổng điểm đã có </strong></p>
                    <h4><?php echo htmlspecialchars($creq['total']); ?></h4>
                </div>
                <div class="info-box">
                    <p><strong>Tổng điểm hiện tại</strong></p>
                    <h4><?php echo htmlspecialchars($creq['pending']); ?></h4>
                </div>
                <div class="info-box">
                    <p><strong>Tổng điểm đã đổi</strong></p>
                    <h4><?php echo htmlspecialchars($creq['changed']); ?></h4>
                </div>
                <div class="info-box">
                    <p><strong>Tổng điểm bị trừ</strong></p>
                    <h4><?php echo htmlspecialchars($creq['deducted']); ?></h4>
                </div>
            <div class="left-column">
                <div class="pending-requests">
                    <h2>Lịch sử thay đổi điểm</h2>
                    <table class="table" id="pending-requests-table">
                        <thead>
                            <tr>
                                <th>Số điểm</th>
                                <th>Chi tiết</th>
                                <th>Người Tặng</th>
                                <th>Thời gian</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($pendingRequests as $request): ?>
                                <tr>
                                    <td>
                                        <?php
                                            // Hiển thị số điểm từ Felicitation, thêm dấu '+' cho điểm dương và '-' cho điểm âm
                                            $point = htmlspecialchars($request['FelicitationPoint']);
                                            echo ($point > 0 ? '+' : '') . $point;
                                        ?>
                                    </td>
                                    <td><?php echo htmlspecialchars($request['FelicitationNoiDung']); ?></td>
                                    <td><?php echo htmlspecialchars($request['FelicitationNguoiTang']); ?></td>
                                    <td><?php echo htmlspecialchars($request['Date']); ?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div id="pending-pagination" class="pagination pagination-wrapper">
                        <?php if ($totalPending > $limit): ?>
                            <?php for ($i = 1; $i <= ceil($totalPending / $limit); $i++): ?>
                                <li class="page-item <?php echo ($i == $pagePending) ? 'active' : ''; ?>">
                                    <a class="page-link" href="#" data-page="<?php echo $i; ?>"><?php echo $i; ?></a>
                                </li>
                            <?php endfor; ?>
                        <?php endif; ?>
                    </div>
            </div>
            
        </div>
        <!-- Cột bên phải -->
        <div class="right-column">
            <?php $monthlyPoints = FelicitationModel::getPoint_Month($_SESSION['user']['EmpID']); ?>
            <div class="stats-chart">
                <h3>Thống kê điểm thưởng theo tháng:</h3>
                <canvas id="rewardChart"></canvas>
            </div>
                <div class="request-list">
                    <h2>Voucher</h2>
                        <div class="Voucher_List">
                            <div class="info-box1">
                                <div class="row1">
                                <div class="left-box">
                                <p><strong>Tổng điểm đã có </strong></p>
                                    <h4><?php echo htmlspecialchars($creq['total']); ?></h4>
                                
                                    <p><strong>Tổng điểm đã có </strong></p>
                                    <h4><?php echo htmlspecialchars($creq['total']); ?></h4>
                                </div>
                                <div class="right-box">
                                    <p><strong>Tổng điểm đã có </strong></p>
                                    <h4><?php echo htmlspecialchars($creq['total']); ?></h4>
                                </div>
                                </div>
                            </div>    
                            <ul class="text-center"><a class="write-request btn btn-primary btn-block custom-btn" href="#" data-req="Chung" loai-req="Nghỉ phép">Danh sách voucher</a></ul>
                        </div>
                                
                </div>
        </div>                
    </div>

    </div>


    <div id="Chung" class="request-form" style="display: none;">
            <h3 class = "text-center">Form điền đơn</h3>
            <br>
            <form>
                <!-- Hàng đầu tiên: Thông tin điền sẵn -->
                <div class="form-row">
                    <div class="form-group">
                        <label for="nguoiGui">Người gửi</label>
                        <input type="text" id="nguoiGui" name="nguoiGui" value="<?php echo htmlspecialchars($_SESSION['user']['HoTen'])?>" readonly>
                    </div>
                    <div class="form-group">
                        <label for="ngayGui">Ngày gửi</label>
                        <input type="text" id="ngayGui" name="ngayGui" readonly>
                    </div>
                    <div class="form-group">
                        <label for="loai">Loại</label>
                        <input type="text" id="loai" name="loai" readonly>
                    </div>
                </div>

                <!-- Hàng thứ hai: Tiêu đề -->
                <div class="form-row">
                    <div class="form-group">
                        <label for="tieuDe">Tiêu đề</label>
                        <input type="text" id="tieuDe" name="tieuDe" placeholder="Nhập tiêu đề">
                    </div>
                </div>

                <!-- Hàng thứ ba: Nội dung -->
                <div class="form-row">
                    <div class="form-group">
                        <label for="noiDung">Nội dung</label>
                        <textarea id="noiDung" name="noiDung" rows="6" placeholder="Nhập nội dung"></textarea>
                    </div>
                </div>

                <button type="submit" class = " btn btn-primary btn-block custom-btn text-center">Gửi đơn</button>
            </form>
    </div>

    <div id="TimeSheet" class="request-form" style="display: none;">
            <h3 class = "text-center">Form điền đơn</h3>
            <br>
            <form>
                <div class="form-row">
                    <div class="form-group">
                        <label for="nguoiGui">Người gửi</label>
                        <input type="text" id="nguoiGui" name="nguoiGui" value="<?php echo htmlspecialchars($_SESSION['user']['HoTen'])?>" readonly>
                    </div>
                    <div class="form-group">
                        <label for="ngayGui">Ngày gửi</label>
                        <input type="text" id="ngayGui" name="ngayGui" readonly>
                    </div>
                    <div class="form-group">
                        <label for="loai">Loại</label>
                        <input type="text" id="loai" name="loai" readonly>
                    </div>
                    <div class="form-group">
                        <label for="timeSheetDropdown">Chọn Time-sheet</label>
                        <select id="timeSheetDropdown" name="timeSheetDropdown">
                            <option value="">Chọn Time-sheet</option>
                        </select>
                    </div>
                </div>

                <div id="project-info" class="form-row" style="display: none;">
                <div class="form-group">
                    <label for="projectID">Project ID</label>
                    <input type="text" id="projectID" name="projectID" readonly>
                </div>
                <div class="form-group">
                    <label for="ngayGiao">Ngày giao</label>
                    <input type="text" id="ngayGiao" name="ngayGiao" readonly>
                </div>
                <div class="form-group">
                    <label for="hanChot">Hạn chót</label>
                    <input type="text" id="hanChot" name="hanChot" readonly>
                </div>
                <div class="form-group">
                    <label for="diemThuong">Điểm thưởng</label>
                    <input type="text" id="diemThuong" name="diemThuong" readonly>
                </div>
                <div class="form-group">
                    <label for="soGioThucHien">Số giờ thực hiện</label>
                    <input type="text" id="soGioThucHien" name="soGioThucHien" readonly>
                </div>
            </div>

                <div class="form-row">
                    <div class="form-group">
                        <label for="tieuDe">Tiêu đề</label>
                        <input type="text" id="tieuDe" name="tieuDe" placeholder="Nhập tiêu đề">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group">
                        <label for="noiDung">Nội dung</label>
                        <textarea id="noiDung" name="noiDung" rows="6" placeholder="Nhập nội dung"></textarea>
                    </div>
                </div>

                <button type="submit" class = " btn btn-primary btn-block custom-btn text-center">Gửi đơn</button>
            </form>
    </div>




    <script>
    const ctx = document.getElementById('rewardChart').getContext('2d');

    // Lấy dữ liệu điểm thưởng từ PHP
    const monthlyPoints = [<?php echo implode(",", $monthlyPoints); ?>];

    // Xác định màu nền dựa trên giá trị của điểm
    const backgroundColors = monthlyPoints.map(point => point < 0 ? 'rgba(255, 99, 132, 0.2)' : 'rgba(75, 192, 192, 0.2)');

    const rewardChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
            datasets: [{
                label: 'Điểm thưởng',
                data: monthlyPoints,
                backgroundColor: backgroundColors, // Sử dụng màu nền tùy thuộc vào giá trị điểm
                borderColor: '#a6a6a6',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

        $(document).ready(function() {
    // Xử lý phân trang cho yêu cầu chờ duyệt
    $(document).on('click', '#pending-pagination .page-link', function(e) {
        e.preventDefault();
        var page = $(this).data('page');
        loadPendingRequests(page, $(this));
    });

    // Xử lý phân trang cho yêu cầu đã duyệt
    $(document).on('click', '#approved-pagination .page-link', function(e) {
        e.preventDefault();
        var page = $(this).data('page');
        loadApprovedRequests(page, $(this));
    });

    function loadPendingRequests(page, element) {
        $.ajax({
            url: 'index.php?action=GetFelicitationPage&ajax=true&pagePending=' + page,
            method: 'GET',
            success: function(response) {
                var data = JSON.parse(response);
                $('#pending-requests-table tbody').html(data.pendingHtml);
                $('#pending-pagination').html(data.pendingPagination);

                // Cập nhật trạng thái active
                var updatedPagination = $('#pending-pagination .page-link[data-page="' + page + '"]');
                updatedPagination.parent().addClass('active');
            },
            error: function() {
                console.error('Không thể tải dữ liệu');
            }
        });
    }

    $('.write-request').on('click', function(e) {
            e.preventDefault();
            var formId = $(this).data('req');
            var loaiReq = $(this).attr('loai-req');
            
            // Ẩn tất cả các form khác
            $('.request-form').hide();
            
            // Hiển thị form tương ứng
            var formElement = $('#' + formId);
            formElement.show();
            formElement[0].scrollIntoView({ behavior: 'smooth' });

            //Lấy loại đơn 
            formElement.find('#loai').val(loaiReq); 

            //Lấy thời gian
            function formatDate(date) {
                var day = ("0" + date.getDate()).slice(-2);
                var month = ("0" + (date.getMonth() + 1)).slice(-2);
                var year = date.getFullYear();
                return day + '/' + month + '/' + year;
            }

            var today = new Date();
            var formattedDate = formatDate(today);

            formElement.find('[name="ngayGui"]').val(formattedDate);

            //Lấy ds time-sheet
            $.ajax({
            url: 'index.php?action=GetRequestPage&ajax=true',
            method: 'GET',
            success: function(response) {
                var data = JSON.parse(response);
                if (data.timeSheets) {
                    var dropdown = $('#timeSheetDropdown');
                    dropdown.empty();
                    dropdown.append('<option value="">Chọn Time-sheet</option>');
                    $.each(data.timeSheets, function(index, timeSheet) {
                        dropdown.append('<option value="' + timeSheet.Time_sheetID + '">' + timeSheet.ProjectID + ' - ' + timeSheet.Time_sheetID + ' - ' + timeSheet.TenDuAn + '</option>');
                    });
                }
            },
            error: function() {
                console.error('Không thể tải dữ liệu');
            }
        });
    });

    $('#timeSheetDropdown').on('change', function() {
        var timeSheetID = $(this).val();
        if (timeSheetID) {
            $.ajax({
                url: 'index.php?action=GetTimeSheetDetails&timeSheetID=' + timeSheetID,
                method: 'GET',
                success: function(response) {
                    var timeSheet = JSON.parse(response);
                    if (timeSheet) {
                        // Hiển thị thông tin dự án
                        $('#project-info').show();
                        
                        // Cập nhật các trường thông tin
                        $('#projectID').val(timeSheet.ProjectID);
                        $('#ngayGiao').val(timeSheet.NgayGiao);
                        $('#hanChot').val(timeSheet.HanChot);
                        $('#diemThuong').val(timeSheet.DiemThuong);
                        $('#soGioThucHien').val(timeSheet.SoGioThucHien);
                        $('#noiDung').val(timeSheet.NoiDung);
                    }
                },
                error: function() {
                    console.error('Không thể tải dữ liệu');
                }
            });
        } else {
            // Ẩn thông tin dự án nếu không có gì được chọn
            $('#project-info').hide();
        }
    });
});

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
