<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="/QLNV_PHP/src/public/css/login.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <main>
        <div class="left-panel">
            <img src="public/img/logo/login.jpg" alt="Ảnh nền" class="background-image">
        </div>
        <div class="right-panel">
            HI
        </div>
    </main>
</body>
</html>