<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="/QLNV_PHP/src/public/css/login.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <main>
        <div class="left-panel">
            <div class="content">
                <h1>Cùng nhau phát triển</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lobortis maximus nunc, ac rhoncus odio congue quis.</p>
            </div>
        </div>
        <div class="right-panel">
            <div class="login-container">
                <h2>Đăng nhập</h2>
                <?php if (isset($error_message)): ?>
                        <p style="color: red;"><?php echo htmlspecialchars($error_message); ?></p>
                <?php endif; ?>
                <form action="index.php?action=checklogin" method="POST">
                    <div class="form-group">
                        <label for="username">Tài khoản</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Mật khẩu</label>
                        <div class="password-wrapper">
                            <input type="password" class="form-control" id="password" name="password" required>
                            <span class="toggle-password">Ẩn</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <a href="/forgot-password" class="forgot-password-link">Quên mật khẩu?</a>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Đăng nhập</button>
                </form>
            </div>
        </div>
    </main>
</body>
</html>
